# Generated by Django 3.0.8 on 2020-08-13 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('labels_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(upload_to=main.models.generate_uuid_filename, verbose_name='Image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_by_user', to=settings.AUTH_USER_MODEL)),
                ('part_of_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_in_project', to='main.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationsJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('on_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations_by_image', to='main.Image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
