# Generated by Django 3.0.8 on 2020-08-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'permissions': (('view_obj', 'View this object'),)},
        ),
    ]
